apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: pytorch-container
    image: sbinnani/pytorch:cuda10.0-cudnn7-runtime-ubuntu18.04
    args: ["sleep", "infinity"]
    resources:
      requests:
        memory: "24Gi"
      limits:
        memory: "64Gi"
        nvidia.com/gpu: 1
